### ISSUE TITLE
error on Tutor tab (even on current master)❗️❗️❗️

### ISSUE THREAD

**Issue by yil578** [CSE110-Fall19-Multiverse/multiverse-project#32]
![image](https://user-images.githubusercontent.com/37963626/69679936-4fcc9800-105e-11ea-94dd-f67233592b0d.png)

**Comment by SCAuFish** [comment]
Resolved in PR #34. Before that, firebase agent was using "set" method instead of "push", which wipes all old posts and mess up with the fields.
